### ISSUE TITLE
Checklist of beta demo requirements

### ISSUE THREAD

**Issue by DerekYu177** [boggy-d/DPM_Competition_Team_17#1]
Lets create a checklist for @EricZimmermann so everyone knows what's going on.

- [x] 1. Accept an input dataset from the server via the wifi connection
- [ ] 2. Localize (the time limit will be waived for the beta demonstration although an attempt will be made to record the localization time to help you in your development process) 
- [ ] 3. Locate a Styrofoam block
- [ ] 4. Demonstrate navigation to the green zone
- [ ] 5. Avoid obstacles on its way.
- [ ] 6. Place the block in the green zone and then terminate its run

@evasuska @boggy-d checklist. Let's fill it out as we go

**Comment by EricZimmermann** [comment]
Code for localization is completed but must be tested
Navigation code has been completed but must be tested
Obstacle avoidance will be neglected for the demo

**Comment by DerekYu177** [comment]
You can tick the boxes when it's done.
